#!/bin/bash

curl -s https://physionet.org/physiotools/matlab/wfdb-app-matlab/wfdb-app-toolbox-0-10-0.zip --output wfdb-app-toolbox-0-10-0.zip
unzip -qq wfdb-app-toolbox-0-10-0.zip
echo 'wfdb-app-toolbox-0-10-0.zip'

matlab -nodisplay -r "\
cd /mcode;\
addpath(pwd);\
savepath;"
